### ISSUE TITLE
 Disconnected from ES http://localhost:9200

### ISSUE THREAD

**Issue by bambangithub** [defenxor/dsiem#173]
i install dsiem with docker on my ubuntu server. when i running dsiem in my local browser, dsiem disconnected from ES. why this happen? and what else i should config?

**Comment by Canon88** [comment]
I also encountered this problem, how can I solve it?

**Comment by mmta** [comment]
If you use the docker-compose method, then by default the UI container will connect to ES in http://localhost:9200.

You can change that by modifying this environment variable in docker-compose.yml:

https://github.com/defenxor/dsiem/blob/ffaf7869b2bedb5fe300956dfe6195bce8bdd9c5/deployments/docker/docker-compose.yml#L58

**Comment by bambangithub** [comment]
> If you use the docker-compose method, then by default the UI container will connect to ES in http://localhost:9200.
> 
> You can change that by modifying this environment variable in docker-compose.yml:
> 
> https://github.com/defenxor/dsiem/blob/ffaf7869b2bedb5fe300956dfe6195bce8bdd9c5/deployments/docker/docker-compose.yml#L58

i've config that, but it still not work

**Comment by mmta** [comment]
First of all you should verify if the browser can indeed access ES, e.g. try opening http://your-es-ip:9200 directly from the browser.

If the above works but Dsiem UI still can't use that address, then the next step is to ensure that ES is configured to allow CORS. The default here only allows localhost (for obvious security reason):

https://github.com/defenxor/dsiem/blob/ffaf7869b2bedb5fe300956dfe6195bce8bdd9c5/deployments/docker/docker-compose.yml#L17

Changing that to ```*``` (temporarily for testing only) may solve the issue.

If the problem isn't CORS, then to troubleshoot this further we will need you to:

- Describe the environment and/or the installation process in more detail, for example did you follow the `docker-compose` method describe in the doc, or is there any step(s) that deviate from that?

- Paste the output of your browser javascript console after triggering the error. For instance, here's how you'd open it on various browsers https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console
