### ISSUE TITLE
About the use of the custom_data field

### ISSUE THREAD

**Issue by Canon88** [defenxor/dsiem#233]
HI DSIEM Team:
     Thank you for your DSIEM project, which I believe will be a great project. I've used OSSIM before, and that's kind of nice to me. could you consider adding dynamic field association matching? For example: **HTTP URL**, **HTTP HOSTNAME**, **HTTP METHOD** some fields?
     Sometimes I want to associate with some HTTP keywords, which is common in business security. I see that you defined **custom_data1**, **custom_data2**, **custom_data3.** Do I need to re-normalize my log if I want to use custom_data? For example: **HTTP URL** rename **custom_data1**?

**Comment by mmta** [comment]
Hi,

Yes, just like in OSSIM you should use `custom_data1` to `custom_data3` to store the content of those extra fields.

We also have `custom_label1` to `custom_label3` to store the field names for display purposes in Dsiem UI. So in your case you could set `custom_label1` to `HTTP-Method` then store the parsed entries like `GET`, `POST`, `PUT`, etc. in `custom_data1`.

**Comment by Canon88** [comment]
Tthank you for your reply. What is the maximum EPS of the association rules engine? Is there a test standard?
