### ISSUE TITLE
Threat Intel enrichment

### ISSUE THREAD

**Issue by HarishHary** [defenxor/dsiem#273]
Hello, Nice work !

Any plan to add another way to add enrichment instead of wise ? 
OpenCTI or MISP directly ?

Best regards,

**Comment by mmta** [comment]
Hi, not at this moment. We do have a plugin architecture that allow this type of contribution from others, and there's an example of doing that in here: https://github.com/defenxor/dsiem/blob/master/docs/ti_vuln_plugins.md#developing-intel-or-vulnerability-lookup-plugin
