### ISSUE TITLE
Alienvault OTX

### ISSUE THREAD

**Issue by emahdij** [defenxor/dsiem#276]
Hi everyone
How can i add alienvault otx to dsiem?or how can to see ossim rules?

**Comment by mmta** [comment]
You should add OTX through Moloch Wise.

As for "OSSIM rules", I assume you mean directives. You will have to create them based on the indices you have on Elasticsearch. See here for more detail and example: https://github.com/defenxor/dsiem/blob/master/docs/directive_and_alarm.md
