### ISSUE TITLE
Exclude some port numbers

### ISSUE THREAD

**Issue by soysaltan** [defenxor/dsiem#295]
When more than five requests are received from the same SRC-IP to different ports of the same DST-IP in one minute, an alarm should be generated.

### Related Rule:
Json-Formatter

```json
{ "directives": [ { "id": 500002, "name": "excludePort_TargetIP", "priority": 3, "disabled": false, "kingdom": "Delivery Attack", "category": "Portscan", "rules": [ { "stage": 1, "name": "rule1", "type": "TaxonomyRule", "product": [ "Intrusion Detection", "Intrusion Prevention", "Firewall" ], "category": "Access", "occurrence": 1, "from": "ANY", "to": "ANY", "port_from": "ANY", "port_to": "ANY", "reliability": 1, "timeout": 0, "protocol": "ANY" }, { "stage": 2, "name": "rule2", "type": "TaxonomyRule", "product": [ "Firewall", "Intrusion Detection", "Intrusion Prevention" ], "category": "Access", "occurrence": 5, "from": ":1", "to": ":1", "port_from": "ANY", "port_to": ":!1", "reliability": 6, "timeout": 60, "protocol": "ANY" } ] } ]}
```
### Error Message:
```json
{Related Line: "port_to": ":!1"}
{"level":"WARN","ts":"2020-09-25T13:07:34.911+0300","msg":"Skipping directive ID 500002 'excludePort_TargetIP' due to error: strconv.Atoi: parsing \":!1\": invalid syntax"}
```

### Request:
- As can be seen above, we encounter an error when we try to exclude some port numbers. Can such a feature be added or if so, how will we do it?

**Comment by mmta** [comment]
Hi, as in OSSIM, you will need to use ```sticky different``` flag for that purpose.

Here's an example of how it's done in Dsiem rule:
https://github.com/defenxor/dsiem/blob/beea45d6b03203ab505eec8a4cfe3e42a1868a40/internal/pkg/dsiem/siem/fixtures/directive1/directives_dsiem-backend-0_testing1.json#L135

In your case, ```SRC_IP``` there should be changed to ```DST_PORT```
