### ISSUE TITLE
ossimcnv does not work

### ISSUE THREAD

**Issue by cntrigkog** [defenxor/dsiem#298]
Hi there,

thank you for your excellent work!

We are trying to transform Ossim directives to dsiem ones using your documentation and although there is no error and ossim produced tsv files are parsed with the command ./ossimcnv -i some.xml -o ./some.json -r ossimref/, the outcome is a file with only the following:

{
  "directives": null
}

Do you maybe know why this is happening?

**Comment by mmta** [comment]
What's the content of your ```ossimref``` directory? if it's empty you will need to run the following script on the OSSIM machine and copy the results to that directory first.

```
#!/bin/bash

echo "select sid, kingdom, category from alienvault.alarm_taxonomy" | ossim-db > ossim_alarm_taxonomy.tsv
echo "select * from alienvault.alarm_kingdoms" | ossim-db > ossim_alarm_kingdom.tsv
echo "select * from alienvault.alarm_categories" | ossim-db > ossim_alarm_category.tsv
echo "select * from alienvault.product_type" | ossim-db > ossim_product_type.tsv
echo "select id,name from alienvault.category" | ossim-db > ossim_product_category.tsv
echo "SELECT id,cat_id,name FROM alienvault.subcategory;" | ossim-db > ossim_product_subcategory.tsv
```

The above TSV files must be in ```ossimref``` for ossimcnv to work.

**Comment by cntrigkog** [comment]
Thanks for your reply!

Actually, we managed to fix it as there was an issue with the ossim .XML files header and once we fixed it the .ossimcv worked flawlessly.

**Comment by lixiaodon** [comment]
Hello, I have met the same mistake, may I ask where you modified it?

**Comment by lixiaodon** [comment]
> Thanks for your reply!
> 
> Actually, we managed to fix it as there was an issue with the ossim .XML files header and once we fixed it the .ossimcv worked flawlessly.

Hello, I have met the same mistake, may I ask where you modified it?

**Comment by Eden4701** [comment]
I added <directives> label to .xml files, and it worked.
