### ISSUE TITLE
Building directives with only one rule

### ISSUE THREAD

**Issue by lenaglas** [defenxor/dsiem#299]
Firstly thank you for the great project!

I wanted to create a directive which only consists of one rule. DSIEM hereby raises the error "Skipping [...] has only one rule and will therefore never expire." I don't quite understand why it is necessary to have more than one rule, especially because it seems to be in OSSIM. Is there a workaround for my problem?

Thank you very much in advance.

**Comment by mmta** [comment]
Hi, the workaround would be to just use the same rule for the 1st and 2nd stage, and set the occurrence to 1 for the first stage. 

I don't remember exactly why that was enforced, but likely something to do with most rules that I've seen having their timeout set to 0 on the first stage.

**Comment by lenaglas** [comment]
Thank you very much for your answer. I ended up just leaving out the line that threw the error and recompiling the project which worked out fine.
