### ISSUE TITLE
dsiem vs built-in elk siem

### ISSUE THREAD

**Issue by entegee** [defenxor/dsiem#311]
Hi, sorry I'm a newbie here. Just want to ask, I just finished install this Dsiem in docker but the thing is, when I want to use the Siem for the alert and incident management function, it said only platinum license can use the feature. So basically, the Dsiem and elk built-in siem feature both need platinum license to run? or somehow I wrongly setup the Dsiem .

**Comment by mmta** [comment]
hi, no dsiem has no dependency on any Elastic platinum features.
