### ISSUE TITLE
[dsiem-demo] how ossec logs are parsed?

### ISSUE THREAD

**Issue by mdalag** [defenxor/dsiem#312]
It is said in the description that 

> Dsiem: preconfigured with a directive that correlates Suricata and Ossec events for the above scenario.

I've found Suricata json plugin and then obtained eve.json from suricata docker container. Fields are matching and everything is clear with that. But there's no plugin for ossec. Is ossec parser hardcoded? How does it works?

**Comment by mmta** [comment]
Hi,

Ossec logs are processed by logstash in the demo with config: https://github.com/defenxor/dsiem/blob/master/demo/docker/conf/logstash/conf.d/50_ossec.conf

The normalized event is then used to generate alarm based on this directive:
https://github.com/defenxor/dsiem/blob/2e793dd8249d5a0ef77593bd14755252ea733d25/demo/docker/conf/dsiem/configs/directives_dsiem-backend_demo.json#L29

Feel free to reopen if you still have follow up questions.

**Comment by mmta** [comment]
oh and in case you're wondering, ossec sends its logs through syslog as configured here:
https://github.com/defenxor/dsiem/blob/2e793dd8249d5a0ef77593bd14755252ea733d25/demo/docker/conf/ossec/ossec.conf#L134
