### ISSUE TITLE
Dsiem-Tools

### ISSUE THREAD

**Issue by MorAywa** [defenxor/dsiem#404]
Hi Guys, I've been exploring this SIEM for a while and I only found that there is only a Dsiem UI web interface to show the alarm list.
Is there any other page that Dsiem have to manage all the configurations by GUI? I found the dsiem-tools on the download page and is there a GUI web face for that ? so we can easily manage the directive tuning for the events or tickets?

Regards,
Aywa

cc : @mmta @rkspx @Cempakers87

**Comment by mmta** [comment]
Unfortunately we don't have the resources to maintain something like that as a public project at this moment :(
