### ISSUE TITLE
why doesn't dsiem accept logs?

### ISSUE THREAD

**Issue by oytir** [defenxor/dsiem#407]
Hi I have problem dsiem or filebeat. I downloaded docker file and installed it, so files are opened and web UI is working well.  However, the problem is that after installation DSIEM works good a litlle period then it does not accept a log from Pfsense pls help me, 
thnks!

**Comment by mmta** [comment]
First you need to make sure that Pfsense logs are ingested into Logstash, then follow the steps from here: https://github.com/defenxor/dsiem/blob/master/docs/dsiem_plugin.md.
